// Generated by CoffeeScript 1.4.0
(function() {
  var $;

  $ = 'boo';

  jQuery(function() {
    var fn, metrics, options, regex;
    fn = function(v) {
      if (v === "") {
        return false;
      }
      return v % 2 === 0;
    };
    regex = /357/;
    metrics = [['#one', 'presence', 'presence'], ['#one', 'email', 'email'], ['#two', 'integer', 'int']];
    options = {
      'submitBtnSelector': '#submit_btn'
    };
    return jQuery("#form").nod(metrics, options);
  });

}).call(this);
